align cache for everything [sc-15446]

diff --git a/.github/workflows/delegation_factory.yml b/.github/workflows/delegation_factory.yml
--- a/.github/workflows/delegation_factory.yml
+++ b/.github/workflows/delegation_factory.yml
@@ -65,9 +65,7 @@ jobs:
       - name: Cache Cargo dependencies
         uses: actions/cache@v4
         with:
-          key: cargo-canisters-delegation_factory
-          restore-keys: |
-            cargo-canisters-
+          key: cargo-canisters
           path: |
             ~/.cargo/registry
             ~/.cargo/git
@@ -77,9 +75,7 @@ jobs:
         uses: actions/cache@v4
         with:
           path: ~/.m2/repository
-          key: maven-canisters-delegation_factory
-          restore-keys: |
-            maven-canisters-
+          key: maven-canisters
 
       - name: Versions
         run: |
@@ -380,124 +376,124 @@ jobs:
           ci_echo_success "Artifact file link: https://${ARTIFACT_BUCKET_NAME}.s3.${AWS_DEFAULT_REGION}.amazonaws.com/${CANISTER_NAME}/${COMPRESS_FILE_NAME}"
           ci_echo_success "Upload Done" >&2
 
-  restore:
-    if: failure()
-    name: restore
-    needs: deploy
-    environment: ${{ github.event.inputs.network_name }}
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
+  # restore:
+  #   if: failure()
+  #   name: restore
+  #   needs: deploy
+  #   environment: ${{ github.event.inputs.network_name }}
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash
 
-    steps:
-      - name: Checkout nfid-wallet-server repo
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout nfid-wallet-server repo
+  #       uses: actions/checkout@v4
 
-      - name: Checkout ci_libs repo
-        uses: actions/checkout@v4
-        with:
-          repository: internet-identity-labs/ci_libs
-          ref: main
-          path: ci_libs
-          token: ${{ secrets.PAT }}
+  #     - name: Checkout ci_libs repo
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: internet-identity-labs/ci_libs
+  #         ref: main
+  #         path: ci_libs
+  #         token: ${{ secrets.PAT }}
 
-      - name: Install dfx
-        run: |
-          export DFX_VERSION=0.23.0
-          export DFXVM_INIT_YES=true
-          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
-          echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
+  #     - name: Install dfx
+  #       run: |
+  #         export DFX_VERSION=0.23.0
+  #         export DFXVM_INIT_YES=true
+  #         sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
+  #         echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
 
-      - name: Install Rust
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          target: wasm32-unknown-unknown
-          override: true
+  #     - name: Install Rust
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #         target: wasm32-unknown-unknown
+  #         override: true
 
-      - name: Versions
-        run: |
-          source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
-          ci_versions
+  #     - name: Versions
+  #       run: |
+  #         source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
+  #         ci_versions
 
-      - name: Checks branch and network_name
-        if: ${{ env.NETWORK_NAME == 'ic' }}
-        run: |
-          source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
+  #     - name: Checks branch and network_name
+  #       if: ${{ env.NETWORK_NAME == 'ic' }}
+  #       run: |
+  #         source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
 
-          if [ "${{ github.event.inputs.confirmation }}" != 'Yes' ]; then
-            ci_echo_error "You have try release to network 'ic' without or with wrong confirmation phrase." >&2
-            exit 1
-          fi
+  #         if [ "${{ github.event.inputs.confirmation }}" != 'Yes' ]; then
+  #           ci_echo_error "You have try release to network 'ic' without or with wrong confirmation phrase." >&2
+  #           exit 1
+  #         fi
 
-          if [ "${GITHUB_REF_TYPE}" != 'tag' ]; then
-            ci_echo_error "Releasing to IC not from tag not allowed." >&2
-            exit 1
-          fi
+  #         if [ "${GITHUB_REF_TYPE}" != 'tag' ]; then
+  #           ci_echo_error "Releasing to IC not from tag not allowed." >&2
+  #           exit 1
+  #         fi
 
-          # https://semver.org/
-          if ! [[ "${GITHUB_REF_NAME}" =~ ${RELEASE_TAG_REGEX} ]]; then
-            ci_echo_error "${GITHUB_REF_TYPE} : '${GITHUB_REF_NAME}' - is not SemVer correct (https://semver.org/)" >&2
-            exit 1
-          fi
+  #         # https://semver.org/
+  #         if ! [[ "${GITHUB_REF_NAME}" =~ ${RELEASE_TAG_REGEX} ]]; then
+  #           ci_echo_error "${GITHUB_REF_TYPE} : '${GITHUB_REF_NAME}' - is not SemVer correct (https://semver.org/)" >&2
+  #           exit 1
+  #         fi
 
-          ci_echo_success "${GITHUB_REF_TYPE} : ${GITHUB_REF_NAME}"
+  #         ci_echo_success "${GITHUB_REF_TYPE} : ${GITHUB_REF_NAME}"
 
-      - name: PRE-RESTORE => Populate env vars.
-        env:
-          DFX_ID_NAME: ${{ vars.DFX_ID_NAME }}
-        run: |
-          source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
+  #     - name: PRE-RESTORE => Populate env vars.
+  #       env:
+  #         DFX_ID_NAME: ${{ vars.DFX_ID_NAME }}
+  #       run: |
+  #         source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
 
-          ci_echo_debug "Getting values from dfx.json" >&2
-          if ! canister_data=$(cat dfx.json | jq -er ".canisters.\"${CANISTER_NAME}\""); then
-            ci_echo_error "Can't found canister '${CANISTER_NAME}' data from dfx.json" >&2
-            exit 1
-          fi
+  #         ci_echo_debug "Getting values from dfx.json" >&2
+  #         if ! canister_data=$(cat dfx.json | jq -er ".canisters.\"${CANISTER_NAME}\""); then
+  #           ci_echo_error "Can't found canister '${CANISTER_NAME}' data from dfx.json" >&2
+  #           exit 1
+  #         fi
 
-          ci_echo_debug "Populating env variables" >&2
-          CANISTER_DID="$(cat dfx.json | jq -er ".canisters.${CANISTER_NAME}.candid")"
-          CANISTER_WASM="$(cat dfx.json | jq -er ".canisters.${CANISTER_NAME}.wasm")"
-          CANISTER_BRANCH="${GITHUB_REF_NAME////-}"
+  #         ci_echo_debug "Populating env variables" >&2
+  #         CANISTER_DID="$(cat dfx.json | jq -er ".canisters.${CANISTER_NAME}.candid")"
+  #         CANISTER_WASM="$(cat dfx.json | jq -er ".canisters.${CANISTER_NAME}.wasm")"
+  #         CANISTER_BRANCH="${GITHUB_REF_NAME////-}"
 
-          ci_echo_debug "Getting dfx identity for network '${NETWORK_NAME}'" >&2
-          DFX_ID_PATH="${HOME}/.config/dfx/identity/${DFX_ID_NAME}"
+  #         ci_echo_debug "Getting dfx identity for network '${NETWORK_NAME}'" >&2
+  #         DFX_ID_PATH="${HOME}/.config/dfx/identity/${DFX_ID_NAME}"
 
-          echo "DFX_ID_NAME=${DFX_ID_NAME}" >> $GITHUB_ENV
-          echo "DFX_ID_PATH=${DFX_ID_PATH}" >> $GITHUB_ENV
+  #         echo "DFX_ID_NAME=${DFX_ID_NAME}" >> $GITHUB_ENV
+  #         echo "DFX_ID_PATH=${DFX_ID_PATH}" >> $GITHUB_ENV
 
-          echo "CANISTER_DID=${CANISTER_DID}" >> $GITHUB_ENV
-          echo "CANISTER_WASM=${CANISTER_WASM}" >> $GITHUB_ENV
-          echo "CANISTER_BRANCH=${CANISTER_BRANCH}" >> $GITHUB_ENV
+  #         echo "CANISTER_DID=${CANISTER_DID}" >> $GITHUB_ENV
+  #         echo "CANISTER_WASM=${CANISTER_WASM}" >> $GITHUB_ENV
+  #         echo "CANISTER_BRANCH=${CANISTER_BRANCH}" >> $GITHUB_ENV
 
-      - name: PRE-RESTORE => Print Vars.
-        run: |
-          source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
-          ci_echo_info "NETWORK_NAME=${NETWORK_NAME}" >&2
-          ci_echo_info "CANISTER_NAME=${CANISTER_NAME}" >&2
-          ci_echo_info "CANISTER_DID=${CANISTER_DID}" >&2
-          ci_echo_info "CANISTER_WASM=${CANISTER_WASM}" >&2
-          ci_echo_info "CANISTER_BRANCH=${CANISTER_BRANCH}" >&2
-          ci_echo_info "DFX_ID_NAME=${DFX_ID_NAME}" >&2
-          ci_echo_info "DFX_ID_PATH=${DFX_ID_PATH}" >&2
+  #     - name: PRE-RESTORE => Print Vars.
+  #       run: |
+  #         source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
+  #         ci_echo_info "NETWORK_NAME=${NETWORK_NAME}" >&2
+  #         ci_echo_info "CANISTER_NAME=${CANISTER_NAME}" >&2
+  #         ci_echo_info "CANISTER_DID=${CANISTER_DID}" >&2
+  #         ci_echo_info "CANISTER_WASM=${CANISTER_WASM}" >&2
+  #         ci_echo_info "CANISTER_BRANCH=${CANISTER_BRANCH}" >&2
+  #         ci_echo_info "DFX_ID_NAME=${DFX_ID_NAME}" >&2
+  #         ci_echo_info "DFX_ID_PATH=${DFX_ID_PATH}" >&2
 
-      - name: PRE-RESTORE => Write identity.
-        env:
-          DFX_ID_KEY: ${{ secrets.DFX_ID_KEY }}
-        run: |
-          source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
+  #     - name: PRE-RESTORE => Write identity.
+  #       env:
+  #         DFX_ID_KEY: ${{ secrets.DFX_ID_KEY }}
+  #       run: |
+  #         source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
 
-          mkdir -p "${DFX_ID_PATH}"
+  #         mkdir -p "${DFX_ID_PATH}"
 
-          ci_echo_warn "Preparing encoded key..." >&2
-          echo "${DFX_ID_KEY}" | base64 -d > "${DFX_ID_PATH}/identity.pem"
+  #         ci_echo_warn "Preparing encoded key..." >&2
+  #         echo "${DFX_ID_KEY}" | base64 -d > "${DFX_ID_PATH}/identity.pem"
 
-      - name: RESTORE => Start the canister.
-        run: |
-          source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
+  #     - name: RESTORE => Start the canister.
+  #       run: |
+  #         source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
 
-          dfx identity use "${DFX_ID_NAME}"
+  #         dfx identity use "${DFX_ID_NAME}"
 
-          ci_echo_info "Starting the canister '${CANISTER_NAME}'" >&2
-          dfx canister start --network "${NETWORK_NAME}" "${CANISTER_NAME}"
+  #         ci_echo_info "Starting the canister '${CANISTER_NAME}'" >&2
+  #         dfx canister start --network "${NETWORK_NAME}" "${CANISTER_NAME}"
